name: CI - Docker Local Build & Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    name: Build & Test Docker Locally
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version
          docker compose version

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=admin" >> .env
          echo "POSTGRES_PASSWORD=password" >> .env
          echo "POSTGRES_DB=miroir_db" >> .env

      - name: Build & Start Docker Containers
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for API to Start
        run: sleep 10

      - name: Health Check API
        run: |
          curl -f http://localhost:8080/health || exit 1

      - name: Run API Tests
        run: |
          docker exec $(docker ps -q -f name=backend) dotnet test --verbosity normal

      - name: Stop & Clean Up Containers
        if: always()
        run: docker compose down
