name: CI - Docker Local Build & Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    name: Build & Test Docker Locally
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version
          docker compose version

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=admin" >> .env
          echo "POSTGRES_PASSWORD=password" >> .env
          echo "POSTGRES_DB=miroir_db" >> .env

      - name: Build & Start Docker Containers
        run: |
          docker compose up -d --build

      - name: Show All Running Containers
        run: docker ps -a

      - name: Show Backend Logs (if available)
        run: |
          CONTAINER_ID=$(docker ps -a --format "{{.ID}} {{.Names}}" | grep "backend" | awk '{print $1}')
          echo "Backend container ID: $CONTAINER_ID"
          docker logs $CONTAINER_ID || true

      - name: Verify backend-api.dll exists in the image
        run: docker run --rm ava-mirror-backend ls -la /app

      - name: Check if Backend Container is Running
        run: docker compose ps backend

      - name: Wait for API to Start
        run: |
          for i in {1..30}; do
            docker compose ps backend
            curl -s http://localhost:8080/health && exit 0
            echo "Waiting for API to start..."
            sleep 2
          done
          echo "API did not start in time" && exit 1

      - name: Stop & Clean Up Containers
        if: always()
        run: docker compose down
