name: CI/CD - Deploy to Firebase & Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore backend-api/

      - name: Build Backend
        run: dotnet build backend-api/ --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test backend-api/ --no-build --verbosity normal

  deploy:
    name: Deploy to Firebase & Cloud Run
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Set Google Cloud Project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          echo "Using GCP Project: ${{ secrets.GCP_PROJECT_ID }}"

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build & Push Docker Image
        run: |
          gcloud builds submit backend-api/ --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/ava-mirror

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ava-mirror \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/ava-mirror \
            --platform managed \
            --region europe-west9 \
            --allow-unauthenticated

      - name: Deploy Firebase Hosting
        run: firebase deploy --debug
