name: CI - Run Tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test-backend:
    name: Test ASP.NET Core Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore backend-api/

      - name: Build
        run: dotnet build backend-api/ --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test backend-api/ --no-build --verbosity normal --logger trx

  test-flutter:
    name: Test Flutter Apps (Miroir & Mobile)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.30'
          channel: stable

      - name: Debug - Check Files
        run: ls -l && ls -l mirror_software && ls -l mirror_mobile_app

      - name: Install Dependencies (Mirror)
        run: flutter pub get
        working-directory: mirror_software

      - name: Install Dependencies (Mobile)
        run: flutter pub get
        working-directory: mirror_mobile_app

      - name: Run Flutter Tests (Mirror)
        run: flutter test
        working-directory: mirror_software

      - name: Run Flutter Tests (Mobile)
        run: flutter test
        working-directory: mirror_mobile_app
