name: CI - Run Tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test-backend:
    name: Test ASP.NET Core Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.2'

      - name: Restore Dependencies
        run: dotnet restore backend-api/

      - name: Build
        run: dotnet build backend-api/ --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test backend-api/ --no-build --verbosity normal --logger trx

  test-flutter:
    name: Test Flutter Apps (Miroir & Mobile)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: stable

      - name: Install Dependencies
        run: |
          flutter pub get
          cd mirror-software && flutter pub get
          cd ../mobile-app && flutter pub get

      - name: Run Flutter Tests (Mirror)
        run: |
          cd mirror-software
          flutter test

      - name: Run Flutter Tests (Mobile)
        run: |
          cd mobile-app
          flutter test
